### ISSUE TITLE
autodock_gpu_128wi: ./cuda/kernels.cu:130: void SetKernelsGpuData(GpuData*): Assertion `0' failed.

### ISSUE THREAD

**Issue by wen1234defeng** [tubiana/screening_protocol#1]
(base) msi790@msi790-MS-7D48:~/机械盘/autodock_gpu_work/AutoDock-GPU-develop$ ad_gpu --ffile ./input/1ac8/derived/1ac8_protein.maps.fld --lfile ./input/1ac8/derived/1ac8_ligand.pdbqt 
AutoDock-GPU version: v1.5-release

Running 1 docking calculation

Cuda device:                              NVIDIA GeForce RTX 4070 Ti
Available memory on device:               11098 MB (total: 11980 MB)

CUDA Setup time 0.043749s

Running Job #1
    Using heuristics: (capped) number of evaluations set to 1132076
    Local-search chosen method is: ADADELTA (ad)
SetKernelsGpuData copy to cData failed no kernel image is available for execution on the device
autodock_gpu_128wi: ./cuda/kernels.cu:130: void SetKernelsGpuData(GpuData*): Assertion `0' failed.
已中止 (核心已转储)

**Comment by tubiana** [comment]
Hi ?

The issue is not related but from autodockGPU and the compatibility with your hardware/software. 
from this line : `RuntimeError: CUDA error: no kernel image is available for execution on the device`, it could be a driver issue.

**Comment by wen1234defeng** [comment]
> 嗨？
> 
> 该问题与 autodockGPU 以及与您的硬件/软件的兼容性无关。 从这一行来看：`RuntimeError: CUDA error: no kernel image is available for execution on the device`，这可能是驱动程序问题。

Thanks! I've tried many methods, but none of them worked, and I keep getting errors. It seems that my CUDA driver and GPU are compatible.
(base) msi790@msi790-MS-7D48:~/下载/cuda-samples/Samples/1_Utilities/deviceQuery
$ ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "NVIDIA GeForce RTX 4070 Ti"
  CUDA Driver Version / Runtime Version          12.4 / 12.4
  CUDA Capability Major/Minor version number:    8.9
  Total amount of global memory:                 11980 MBytes (12562399232 bytes)
  (060) Multiprocessors, (128) CUDA Cores/MP:    7680 CUDA Cores
  GPU Max Clock rate:                            2610 MHz (2.61 GHz)
  Memory Clock rate:                             10501 Mhz
  Memory Bus Width:                              192-bit
  L2 Cache Size:                                 50331648 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total shared memory per multiprocessor:        102400 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1536
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device supports Managed Memory:                Yes
  Device supports Compute Preemption:            Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 12.4, CUDA Runtime Version = 12.4, NumDevs = 1
Result = PASS
